# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
