# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_projects', '0002_project_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(default=''),
        ),
    ]
