# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='can_add_new_choice',
            field=models.BooleanField(default=True),
        ),
    ]
